Feat: Add Back to Top
DevQuestNiort/devquest-website pull request #48
Opened 2024-02-05 22:03 UTC by Tisamu

Closes #27

2024-02-05 22:05 UTC, Lithyon commented
prettier . --write

2024-02-05 22:07 UTC, Lithyon requested changes

2024-02-05 22:07 UTC, Lithyon commented on devquest-website.iml
.gitignore ?

2024-02-05 22:40 UTC, Lithyon approved these changes

2024-02-11 07:42 UTC, Ithrandil commented on src/presentation/styles/icons/dq-codes.css
> +.icon-up-big:before {
@Tisamu J'ai essayé de comprendre par moi même quand j'ai pull le repo sans réussir à trouver de réponse donc je préfère passer pour un con un petit peu et apprendre.
Je comprend pas tout ce qu'il y a dans ce dossier. C'est des unicode qui représentent les icones?

2024-02-11 07:43 UTC, Ithrandil commented on src/presentation/pages/Home/Home.module.scss
> +  //width: 100vw;
pas de commentaires

2024-02-11 07:43 UTC, Ithrandil approved these changes

2024-02-24 16:23 UTC, Ithrandil commented
J'ai essayé de transférer ta branche avec la nouvelle archi mais vu que je ne comprend rien du tout au truc qui se passent dans les fichiers css j'ai laissé tomber (cf mes com du dessus). J'ai testé en local, l'idée était d'utiliser cet icone pour le back to top https://www.figma.com/file/W54G9XCyN7R8zUnOlIKI5M/DEVQUEST?type=design&node-id=72-808&mode=design&t=6VbRRkJO65reRsHS-0

2024-03-22 07:48 UTC, closed without merging